#! /bin/bash

SCRIPTDIR=/usr/share/opi-postsetup/scripts

LOGNAME="OPI Postsetup"
LOGLEVEL=8

source /usr/share/kgp-bashlibrary/scripts/kgp-logging.sh

log_notice "starting"

if [ -e /etc/opi/firstboot ]
then
	log_notice "Processing $SCRIPTDIR"
	export DEBIAN_FRONTEND=noninteractive
	run-parts $SCRIPTDIR
	rm -f /etc/opi/firstboot
	log_notice "Processing completed"
else
	log_debug "Not first boot, skipping script processing"
fi
log_notice "terminating"
