#! /bin/bash

/usr/sbin/service mysql start

adm_pass=$(pwgen -N1 -s 24)

mysqladmin -u root password $adm_pass

/usr/sbin/service mysql stop

cat > /root/.my.cnf <<eof
[client]
user=root
password=$adm_pass
eof

chmod 0600 /root/.my.cnf
