#! /bin/bash

logger "Running post setup reconfigure"

# We need mysql to be started before we can proceed
while ! systemctl -q is-active mysql
do
	logger "Waiting for mysql to start up"
	sleep 1
done

logger "Running reconfigure of any unconfigured packages"

export DEBIAN_FRONTEND=noninteractive DEBCONF_NONINTERACTIVE_SEEN=true
export LC_ALL=C LANGUAGE=C LANG=C

dpkg --configure -a

logger "Reconfigure completed"
