#! /bin/bash

STARTED=1

if systemctl -q is-active mysql
then
	STARTED=0
else
	systemctl start mysql
fi

export DEBIAN_FRONTEND=noninteractive DEBCONF_NONINTERACTIVE_SEEN=true
export LC_ALL=C LANGUAGE=C LANG=C

dpkg --configure -a

if [ $STARTED -eq 1 ]
then
	systemctl stop mysql
fi
